### PR TITLE
Miscellaneous fixes for GPU build and test:

### PR DESCRIPTION
**Pull request by japlews**
- Enable building with nvcc_wrapper for ease of linking in ArborX with
    correct Kokkos configuration.
  - Do not call Kokkos::initialize() and finalize() through search interface
    more than once in unit tests.
  - Create an object 'otm_scope' intended to protect against calling
    initialize()/finalize() more than once, and move search initialize and
    finalize calls out to main().
  - Fix function definition order to properly resolve auto types.

### CODE REVIEW

**Comment by japlews** [comment]
@ibaned I find using nvcc_wrapper pretty unsatisfactory given the now native support of CUDA builds in CMake...but it's required for a Trilinos dependency. Could also try clang as a compiler wrapper. Just wanted to get your take, if you have thoughts on a more elegant solution here.

**Comment by ibaned** [comment]
@japlews in my main project I've been able to build and install Kokkos using `nvcc_wrapper` and then build and link my application with only native CMake support for CUDA.

I won't delay this PR on that though, if you want to improve this later on I can merge subsequent PRs.

**Comment by japlews** [comment]
@ibaned I agree that it should be possible, and yet when I set `target_link_libraries(liblgr PUBLIC ArborX::ArborX)` it pulls in all `Kokkos_CXX_FLAGS`. Convenient, but not ideal if you're not compiling with a NVCC wrapper compiler such as clang or nvcc_wrapper. This is a potential feature request to submit to the ArborX team.

**Comment by ibaned** [comment]
Yep, the `ArborX` project team is now also part of the Kokkos team, and I think those people are in favor of getting rid of `nvcc_wrapper` in the long run.

**Pull request merged**
